### ISSUE TITLE
JSONObject returns null in PIT test

### ISSUE THREAD

**Issue by karti-8100** [koral--/gradle-pitest-plugin#91]
Hello,

Firstly, i really appreciate your work on the android fork of gradle-pitest-plugin.

While running unit tests, i was able to create JSONObject but not in PIT test.
I have added json library as test dependency and test options as well

testImplementation "org.json:json:20180813"

testOptions {
        unitTests.returnDefaultValues = true
        } 
        
Added simple test like this
@Test
    fun `test json object`() {
        val jsonObject = JSONObject("{\"id\": xyz}")
        assertNotNull(jsonObject)
    }

**Comment by koral--** [comment]
I could not reproduce this on the current version.
Could you fork this repo and add a failing functional test?

**Comment by karti-8100** [comment]
Thanks for looking into it.

Here is my sample [repo](https://github.com/karti-8100/sample-repo), and failing test in PITEST was here [test](https://github.com/karti-8100/sample-repo/blob/fff1e859525b4254dac28e005f8140b6c782ca97/app/src/test/java/com/example/sample/NumberUtilsTest.kt#L29)

**Comment by koral--** [comment]
Thanks. I was able to reproduce that.
For now I see 2 solutions:
1. Add the json library dependency to the pitest classpath, e.g. by using the following snippet in your `app/build.gradle` file:
```
buildscript {
    configurations.create("pitestTestCompile")
    dependencies {
        pitestTestCompile 'org.json:json:20180813'
    }
}
```
Note that it has to be on very top (before the `plugins` block) and `Compile` suffix is intentional here (`Implementation` won't work here unlike the AGP update assistant suggests).

2. If you are not using any class from the Android framework (included in `android.jar`) in your tests except those provided by json library you can add `excludeMockableAndroidJar = true` to your `pitest` block. In such case you can also remove `unitTests.returnDefaultValues = true`.

I will keep this issue open for a while and investigate if it can be handled by the plugin itself.

**Comment by karti-8100** [comment]
@koral-- it worked, Thanks for looking into.
